build:
  image: node
  commands:
    - npm install
    - npm run build:production
cache:
  mount:
    - node_modules
publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    registry: registry.aliyuncs.com
    repo: xueqingxiao/home
    tag: latest
    file: Dockerfile
    mirror: https://19tyykg1.mirror.aliyuncs.com
    when:
      branch: master
deploy:
  ssh:
    host: 47.88.189.75
    user: root
    when:
      branch: master
    commands:
      - docker pull registry.aliyuncs.com/xueqingxiao/home
      - docker run --rm registry.aliyuncs.com/xueqingxiao/home cp -rf home /data/home
 