pipeline:
  build:
    image: node
    commands:
      - npm install yarn -g
      - yarn install
      - yarn build:production

  publish:
    image: plugins/docker
    registry: registry.cn-hangzhou.aliyuncs.com
    repo: registry.cn-hangzhou.aliyuncs.com/xueqingxiao/xueqingxiao.tech
    username: ${REGISTRY_USERNAME}
    password: ${REGISTRY_PASSWORD}
    tags: latest
      
  deploy:
    image: appleboy/drone-ssh
    host: xueqingxiao.tech
    user: ${SSH_USERNAME}
    password: ${SSH_PASSWORD}
    script:
      - docker pull registry.cn-hangzhou.aliyuncs.com/xueqingxiao/xueqingxiao.tech:latest
      - docker run --rm --volumes-from=nginx registry.cn-hangzhou.aliyuncs.com/xueqingxiao/xueqingxiao.tech:latest cp -rf home /webapps
